server:
  port: 8888

info:
  name: ${spring.application.name}
  description: ${spring.application.name} service

management:
  context-path: /admin
  security:
    enabled: false
  info:
    build:
      enabled: true
    git:
      mode: full

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /${management.context-path}/info
    healthCheckUrlPath: /${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://cloud-demo-registry:8761/eureka/
    healthcheck:
          enabled: true
    enabled: true

spring:
  rabbitmq:
    host: rabbitmq
    username: admin
    password: password
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/jinternals/cloud-demo-config
          basedir: target/config
          force-pull: true

security:
  user:
    password: password




---
spring:
  profiles: development
  rabbitmq:
    host: localhost
    username: admin
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
