version: '3'

services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./infra/rabbitmq/:/var/lib/rabbitmq
