version: '2'
services:

  cloud-demo-config:
    image: mradul/cloud-demo-config:${TAG}
    container_name: cloud-demo-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  cloud-demo-registry:
    image: mradul/cloud-demo-registry:${TAG}
    container_name: cloud-demo-registry
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
